services:
  hermes-agent:
    image: ${HERMES_REPO:-nousresearch/hermes-agent"}:${HERMES_TAG:-latest}
    # Since v2026.4.23, we need user root if we want chown/chgid/exec as a given user
    user: "0"
    # entrypoint: ["/bin/bash", "/path/to/my/custom-script.sh"]
    container_name: hermes-agent
    restart: unless-stopped
    command: gateway run
    ports:
      - "${HERMES_PORT:-8642}:8642"
      - "${DASHBOARD_PORT:-9119}:9119"
    volumes:
      - "${DATA_DIR:-./data}:/opt/data"
      # - "${PROJECTS_ROOT:-./data}:/opt/data/projects"
      # - "./data/SOUL.md:/opt/data/SOUL.yaml" # TODO: Should probably be covered by data folder once we feel confident with kopia
      # - "./data/config.yaml:/opt/data/config.yaml"
      # - "./entrypoint.sh:/opt/hermes/docker/entrypoint.sh"
      # - ~/.hermes:/opt/data
    env_file:
      - path: ./app.env
        required: true
      - path: ./secret.env
        required: true
